import { db } from '../lib/db/index'
import { warningLights } from '../lib/db/schema'

// BYD warning lights data sourced from dianchema.com
// brand-wide lights have model_id = null
// model-specific lights have model_id set

const BYD_LIGHTS = [
  // ── Battery & Charging（电池与充电）──────────────────────────────────────────
  {
    brand_id: 'byd', model_id: null,
    category: 'Battery & Charging',
    name_en: 'Check On-Board Charging System', name_cn: '请检查车载充电系统',
    severity: 'WARNING',
    description_en: 'The on-board charger (OBC) has detected a fault. AC charging may be unavailable.',
    causes: ['Charging cable fault', 'OBC internal fault', 'Communication error between OBC and BMS'],
    can_drive: 'caution',
    action_en: 'Avoid AC charging until inspected. DC fast charging may still work. Book a dealer appointment.',
  },
  {
    brand_id: 'byd', model_id: null,
    category: 'Battery & Charging',
    name_en: 'High Voltage Battery Overtemperature', name_cn: '动力电池过热警告灯',
    severity: 'CRITICAL',
    description_en: 'The high-voltage traction battery has exceeded safe operating temperature.',
    causes: ['Extreme ambient temperature', 'Blocked battery cooling vents', 'Coolant system fault', 'Rapid charging in hot conditions'],
    can_drive: 'no',
    action_en: 'Stop driving immediately. Park in shade with windows open. Do not charge. Contact dealer.',
  },
  {
    brand_id: 'byd', model_id: null,
    category: 'Battery & Charging',
    name_en: 'High Voltage Battery Fault', name_cn: '动力电池故障警告灯',
    severity: 'CRITICAL',
    description_en: 'A fault has been detected in the high-voltage battery pack or battery management system (BMS).',
    causes: ['BMS internal fault', 'Cell voltage imbalance', 'High voltage isolation fault', 'Wiring harness issue'],
    can_drive: 'no',
    action_en: 'Do not drive. Have the vehicle recovered to a BYD authorised dealer immediately.',
  },
  {
    brand_id: 'byd', model_id: null,
    category: 'Battery & Charging',
    name_en: 'Low Battery Warning', name_cn: '动力电池电量低警告灯',
    severity: 'INFO',
    description_en: 'The traction battery state of charge is critically low (typically below 10–15%).',
    causes: ['Battery depleted during driving'],
    can_drive: 'caution',
    action_en: 'Charge as soon as possible. Reduce speed to extend remaining range.',
  },
  {
    brand_id: 'byd', model_id: null,
    category: 'Battery & Charging',
    name_en: '12V Supply System Fault', name_cn: '低压供电系统故障警告灯',
    severity: 'WARNING',
    description_en: 'The 12V low-voltage supply system has a fault. This powers vehicle electronics.',
    causes: ['12V auxiliary battery weak or failed', 'DC-DC converter fault', 'Wiring fault'],
    can_drive: 'caution',
    action_en: 'Book a service appointment promptly. Vehicle may not start if 12V battery fails completely.',
  },
  {
    brand_id: 'byd', model_id: null,
    category: 'Battery & Charging',
    name_en: 'Charging Connected Indicator', name_cn: '动力电池充电连接指示灯',
    severity: 'INFO',
    description_en: 'The charge cable is connected and charging is in progress or the vehicle is plugged in.',
    causes: ['Normal charging operation'],
    can_drive: 'no',
    action_en: 'Normal indicator. Unplug before driving.',
  },

  // ── Braking System（制动系统）───────────────────────────────────────────────
  {
    brand_id: 'byd', model_id: null,
    category: 'Braking System',
    name_en: 'Check ESC System', name_cn: '请检查ESC系统',
    severity: 'WARNING',
    description_en: 'The Electronic Stability Control system requires inspection.',
    causes: ['ESC module fault', 'Wheel speed sensor fault', 'Low brake fluid'],
    can_drive: 'caution',
    action_en: 'Drive carefully avoiding sharp manoeuvres. Book a service appointment.',
  },
  {
    brand_id: 'byd', model_id: null,
    category: 'Braking System',
    name_en: 'ABS Fault', name_cn: 'ABS故障警告灯',
    severity: 'WARNING',
    description_en: 'The Anti-lock Braking System has a fault. Normal braking still works but ABS is disabled.',
    causes: ['Wheel speed sensor fault', 'ABS module fault', 'Wiring fault'],
    can_drive: 'caution',
    action_en: 'Drive cautiously. Avoid emergency braking situations. Book a service appointment soon.',
  },
  {
    brand_id: 'byd', model_id: null,
    category: 'Braking System',
    name_en: 'ESC Fault', name_cn: 'ESC故障警告灯',
    severity: 'WARNING',
    description_en: 'The Electronic Stability Control system has a fault and is disabled.',
    causes: ['ESC module fault', 'Steering angle sensor fault', 'Wheel speed sensor fault'],
    can_drive: 'caution',
    action_en: 'Drive carefully. Avoid high speeds and sharp cornering. Book a service appointment.',
  },
  {
    brand_id: 'byd', model_id: null,
    category: 'Braking System',
    name_en: 'ESC OFF', name_cn: 'ESC OFF警告灯',
    severity: 'INFO',
    description_en: 'Electronic Stability Control has been manually switched off.',
    causes: ['Driver disabled ESC via button'],
    can_drive: 'yes',
    action_en: 'Re-enable ESC via the ESC button unless intentionally disabled (e.g., for off-road use).',
  },
  {
    brand_id: 'byd', model_id: null,
    category: 'Braking System',
    name_en: 'Parking System Fault', name_cn: '驻车系统故障警告灯',
    severity: 'WARNING',
    description_en: 'The electronic parking brake (EPB) system has a fault.',
    causes: ['EPB actuator fault', 'EPB control module fault', 'Brake pad wear'],
    can_drive: 'caution',
    action_en: 'Ensure vehicle is on level ground before exiting. Book a service appointment immediately.',
  },
  {
    brand_id: 'byd', model_id: null,
    category: 'Braking System',
    name_en: 'Automatic Emergency Braking Alert', name_cn: '自动紧急制动报警警告灯',
    severity: 'WARNING',
    description_en: 'The Automatic Emergency Braking (AEB) system has triggered or has a fault.',
    causes: ['AEB activation during near-collision', 'AEB sensor blocked or dirty', 'System fault'],
    can_drive: 'caution',
    action_en: 'If triggered by near-collision, check for damage. If fault light remains, book a service.',
  },
  {
    brand_id: 'byd', model_id: null,
    category: 'Braking System',
    name_en: 'Brake System Fault', name_cn: '制动系统故障警告灯',
    severity: 'CRITICAL',
    description_en: 'A critical fault has been detected in the brake system.',
    causes: ['Low brake fluid', 'Brake line leak', 'Brake booster fault', 'Brake pad severely worn'],
    can_drive: 'no',
    action_en: 'Stop safely immediately. Do not drive. Have the vehicle inspected before moving.',
  },

  // ── Driver Assist（驾驶辅助）────────────────────────────────────────────────
  {
    brand_id: 'byd', model_id: null,
    category: 'Driver Assist',
    name_en: 'Driver Assist Limited (FCW/AEB)', name_cn: '驾驶辅助功能受限（FCW/AEB）',
    severity: 'INFO',
    description_en: 'Forward Collision Warning and Automatic Emergency Braking are temporarily unavailable.',
    causes: ['Camera/radar blocked by dirt, rain, or fog', 'Sensor temperature out of range', 'System calibration required after windscreen replacement'],
    can_drive: 'yes',
    action_en: 'Clean sensors. If persists, book calibration at a dealer.',
  },
  {
    brand_id: 'byd', model_id: null,
    category: 'Driver Assist',
    name_en: 'Driver Assist Limited (BSD)', name_cn: '驾驶辅助功能受限（BSD）',
    severity: 'INFO',
    description_en: 'Blind Spot Detection is temporarily unavailable.',
    causes: ['Rear radar sensors blocked or dirty', 'Sensor fault'],
    can_drive: 'yes',
    action_en: 'Clean rear sensors. If persists, book a service.',
  },
  {
    brand_id: 'byd', model_id: null,
    category: 'Driver Assist',
    name_en: 'Driver Assist Limited (LDW/LDP)', name_cn: '驾驶辅助功能受限（LDW/LDP）',
    severity: 'INFO',
    description_en: 'Lane Departure Warning and Lane Departure Prevention are temporarily unavailable.',
    causes: ['Front camera blocked', 'Poor lane marking visibility', 'System fault'],
    can_drive: 'yes',
    action_en: 'Clean windscreen around camera. If persists, book calibration.',
  },
  {
    brand_id: 'byd', model_id: null,
    category: 'Driver Assist',
    name_en: 'Adaptive Cruise Control Fault', name_cn: '自适应巡航故障警告灯',
    severity: 'WARNING',
    description_en: 'The Adaptive Cruise Control system has a fault and is unavailable.',
    causes: ['Front radar blocked or dirty', 'Radar module fault', 'Wiring fault'],
    can_drive: 'yes',
    action_en: 'Clean front bumper radar area. Book a service if light remains.',
  },
  {
    brand_id: 'byd', model_id: null,
    category: 'Driver Assist',
    name_en: 'Blind Spot Monitor Fault', name_cn: '盲区监测故障警告灯',
    severity: 'WARNING',
    description_en: 'The Blind Spot Monitoring system has a fault.',
    causes: ['Rear radar sensor fault', 'Wiring fault'],
    can_drive: 'yes',
    action_en: 'Book a service appointment.',
  },
  {
    brand_id: 'byd', model_id: null,
    category: 'Driver Assist',
    name_en: 'Lane Assist Fault', name_cn: '车道辅助系统故障警告灯',
    severity: 'WARNING',
    description_en: 'The Lane Keeping Assist system has a fault.',
    causes: ['Front camera fault', 'System software fault'],
    can_drive: 'yes',
    action_en: 'Book a service appointment.',
  },
  {
    brand_id: 'byd', model_id: null,
    category: 'Driver Assist',
    name_en: 'Adaptive Headlight Fault', name_cn: '自适应前照灯故障警告灯',
    severity: 'WARNING',
    description_en: 'The adaptive headlight levelling or swivelling system has a fault.',
    causes: ['Headlight actuator fault', 'Ride height sensor fault'],
    can_drive: 'yes',
    action_en: 'Book a service. Headlights remain on but without auto-levelling.',
  },
  {
    brand_id: 'byd', model_id: null,
    category: 'Driver Assist',
    name_en: 'Driver Monitoring Fault', name_cn: '驾驶员监测辅助系统故障警告灯',
    severity: 'INFO',
    description_en: 'The Driver Monitoring System (DMS) has a fault.',
    causes: ['Interior camera blocked or dirty', 'System fault'],
    can_drive: 'yes',
    action_en: 'Clean interior camera lens. Book a service if persists.',
  },

  // ── Powertrain（动力系统）───────────────────────────────────────────────────
  {
    brand_id: 'byd', model_id: null,
    category: 'Powertrain',
    name_en: 'EV Function Limited', name_cn: 'EV功能受限',
    severity: 'WARNING',
    description_en: 'The electric drive system is operating in a reduced-power mode.',
    causes: ['Battery temperature too high or low', 'Drive motor fault', 'Inverter fault', 'Overheating protection active'],
    can_drive: 'caution',
    action_en: 'Reduce speed and load. Allow vehicle to cool if overheated. Book a service if persists.',
  },
  {
    brand_id: 'byd', model_id: null,
    category: 'Powertrain',
    name_en: 'Powertrain Fault', name_cn: '动力系统故障警告灯',
    severity: 'CRITICAL',
    description_en: 'A critical fault has been detected in the powertrain system.',
    causes: ['Drive motor fault', 'Inverter fault', 'High voltage system fault'],
    can_drive: 'no',
    action_en: 'Stop safely. Do not drive. Contact dealer for recovery.',
  },
  {
    brand_id: 'byd', model_id: null,
    category: 'Powertrain',
    name_en: 'Drive Power Limited', name_cn: '驱动功率限制警告灯',
    severity: 'WARNING',
    description_en: 'Drive power is being limited by the system (limp mode).',
    causes: ['Motor overtemperature', 'Battery overtemperature', 'System protection active'],
    can_drive: 'caution',
    action_en: 'Reduce driving demands. Pull over and allow cooling if possible. Book a service.',
  },

  // ── Steering & Chassis（转向与底盘）─────────────────────────────────────────
  {
    brand_id: 'byd', model_id: null,
    category: 'Steering & Chassis',
    name_en: 'Check HDC System', name_cn: '请检查HDC系统',
    severity: 'WARNING',
    description_en: 'The Hill Descent Control system requires inspection.',
    causes: ['HDC module fault', 'Wheel speed sensor fault'],
    can_drive: 'caution',
    action_en: 'Avoid steep downhill driving until inspected. Book a service.',
  },
  {
    brand_id: 'byd', model_id: null,
    category: 'Steering & Chassis',
    name_en: 'Steering System Fault', name_cn: '转向系统故障警告灯',
    severity: 'CRITICAL',
    description_en: 'The Electric Power Steering (EPS) system has a fault. Steering may be very heavy.',
    causes: ['EPS motor fault', 'EPS control module fault', 'Steering angle sensor fault', 'Low 12V voltage'],
    can_drive: 'no',
    action_en: 'Stop safely. Steering will require more effort. Do not drive. Contact dealer.',
  },
  {
    brand_id: 'byd', model_id: null,
    category: 'Steering & Chassis',
    name_en: 'Tyre Pressure Fault', name_cn: '胎压故障警告灯',
    severity: 'WARNING',
    description_en: 'One or more tyres has low pressure or the TPMS has a fault.',
    causes: ['Puncture or slow tyre leak', 'Tyre pressure below minimum (typically 35 PSI)', 'TPMS sensor battery dead', 'Temperature change causing pressure drop'],
    can_drive: 'caution',
    action_en: 'Check tyre pressures immediately. Inflate to recommended pressure (see door jamb sticker). If puncture, replace or repair.',
  },

  // ── Safety（安全系统）──────────────────────────────────────────────────────
  {
    brand_id: 'byd', model_id: null,
    category: 'Safety',
    name_en: 'Airbag Fault', name_cn: '安全气囊故障警告灯',
    severity: 'WARNING',
    description_en: 'A fault has been detected in the airbag / SRS system. Airbags may not deploy in a crash.',
    causes: ['Airbag control module fault', 'Seat belt pre-tensioner fault', 'Wiring fault under seat', 'Clock spring fault'],
    can_drive: 'caution',
    action_en: 'Book a service immediately. Occupant protection is compromised.',
  },
  {
    brand_id: 'byd', model_id: null,
    category: 'Safety',
    name_en: 'Seatbelt Reminder', name_cn: '安全带未系指示灯',
    severity: 'INFO',
    description_en: 'One or more occupants have not fastened their seatbelt.',
    causes: ['Seatbelt not buckled'],
    can_drive: 'caution',
    action_en: 'Fasten all seatbelts before driving.',
  },
  {
    brand_id: 'byd', model_id: null,
    category: 'Safety',
    name_en: 'Smart Key System Warning', name_cn: '智能钥匙系统警告灯',
    severity: 'WARNING',
    description_en: 'The smart key / keyless entry system has a fault or the key battery is low.',
    causes: ['Key fob battery low', 'Key module fault', 'Signal interference'],
    can_drive: 'caution',
    action_en: 'Replace key fob battery. If persists, book a service.',
  },

  // ── Lighting（灯光系统）────────────────────────────────────────────────────
  {
    brand_id: 'byd', model_id: null,
    category: 'Lighting',
    name_en: 'Headlight Fault', name_cn: '前照灯故障警告灯',
    severity: 'WARNING',
    description_en: 'A headlight bulb or headlight system has a fault.',
    causes: ['LED headlight module fault', 'Headlight control unit fault', 'Wiring fault'],
    can_drive: 'caution',
    action_en: 'Check headlights are working. Book a service — LED headlights are dealer-replaced.',
  },
  {
    brand_id: 'byd', model_id: null,
    category: 'Lighting',
    name_en: 'Auto High Beam Fault', name_cn: '智能远近光灯故障指示灯',
    severity: 'INFO',
    description_en: 'The automatic high beam / intelligent headlight system has a fault.',
    causes: ['Front camera dirty or blocked', 'System fault'],
    can_drive: 'yes',
    action_en: 'Clean windscreen around camera. Use manual high beam control. Book a service if persists.',
  },

  // ── Thermal Management（热管理系统）─────────────────────────────────────────
  {
    brand_id: 'byd', model_id: null,
    category: 'Thermal Management',
    name_en: 'Coolant Temperature High', name_cn: '冷却液温度过高警告灯',
    severity: 'CRITICAL',
    description_en: 'The coolant temperature has exceeded the safe operating threshold.',
    causes: ['Coolant level low', 'Coolant leak', 'Coolant pump fault', 'Thermostat fault', 'Blocked radiator'],
    can_drive: 'no',
    action_en: 'Stop immediately. Do not open the bonnet immediately. Allow to cool. Check coolant level. Call for assistance.',
  },
  {
    brand_id: 'byd', model_id: null,
    category: 'Thermal Management',
    name_en: 'Motor Overtemperature', name_cn: '电机过热警告灯',
    severity: 'WARNING',
    description_en: 'The drive motor has exceeded its safe operating temperature.',
    causes: ['Extended high-load driving', 'Towing at maximum capacity', 'Cooling system fault'],
    can_drive: 'caution',
    action_en: 'Reduce speed and load immediately. Pull over and allow cooling. If persists, book a service.',
  },
  {
    brand_id: 'byd', model_id: null,
    category: 'Thermal Management',
    name_en: 'Motor Coolant Temperature High', name_cn: '电机冷却液温度过高警告灯',
    severity: 'WARNING',
    description_en: 'The motor cooling circuit coolant temperature is too high.',
    causes: ['Motor cooling pump fault', 'Coolant level low in motor circuit', 'Cooling fan fault'],
    can_drive: 'caution',
    action_en: 'Reduce driving load. Book a service promptly.',
  },

  // ── Body Electronics（车身电子）────────────────────────────────────────────
  {
    brand_id: 'byd', model_id: null,
    category: 'Body Electronics',
    name_en: 'Vehicle Network Fault', name_cn: '车辆网络故障',
    severity: 'WARNING',
    description_en: 'A fault has been detected in the vehicle CAN bus network.',
    causes: ['CAN bus communication error', 'Control module fault', 'Wiring or connector fault'],
    can_drive: 'caution',
    action_en: 'Book a dealer appointment. Multiple systems may be affected.',
  },
  {
    brand_id: 'byd', model_id: null,
    category: 'Body Electronics',
    name_en: 'Check Headlight System', name_cn: '请检查前照灯系统',
    severity: 'WARNING',
    description_en: 'The headlight control system requires inspection.',
    causes: ['Headlight levelling motor fault', 'Headlight control module fault'],
    can_drive: 'yes',
    action_en: 'Book a service appointment.',
  },
  {
    brand_id: 'byd', model_id: null,
    category: 'Body Electronics',
    name_en: 'Master Warning Light', name_cn: '主告警指示灯',
    severity: 'WARNING',
    description_en: 'A general system warning. Check the vehicle display for the specific message.',
    causes: ['Various — check instrument cluster message'],
    can_drive: 'caution',
    action_en: 'Read the accompanying message on the display screen. Follow specific guidance shown.',
  },

  // ── Engine System（发动机系统）— DM-i models only ───────────────────────────
  {
    brand_id: 'byd', model_id: null,
    category: 'Engine System',
    name_en: 'Engine Accessory Function Limited', name_cn: '发动机附件功能受限',
    severity: 'INFO',
    description_en: 'An engine accessory (alternator, A/C compressor, etc.) is operating in reduced mode.',
    causes: ['Accessory belt fault', 'Alternator fault', 'A/C compressor issue'],
    can_drive: 'caution',
    action_en: 'Book a service appointment. DM-i models use engine for charging in some conditions.',
  },
  {
    brand_id: 'byd', model_id: null,
    category: 'Engine System',
    name_en: 'Emission Fault Indicator', name_cn: '排放故障指示灯',
    severity: 'WARNING',
    description_en: 'The engine emission control system has detected a fault (DM-i models).',
    causes: ['Catalytic converter fault', 'Oxygen sensor fault', 'EGR valve fault'],
    can_drive: 'caution',
    action_en: 'Book a service appointment. Vehicle may fail emissions testing.',
  },
  {
    brand_id: 'byd', model_id: null,
    category: 'Engine System',
    name_en: 'Engine Fault Warning', name_cn: '发动机故障警告灯',
    severity: 'WARNING',
    description_en: 'The engine control unit has detected a fault (DM-i / DM-p models).',
    causes: ['Various engine faults — read DTC codes with a scanner', 'Fuel system fault', 'Ignition fault'],
    can_drive: 'caution',
    action_en: 'Book a dealer service. For DM-i models, EV mode may still work — avoid engine-on driving.',
  },
  {
    brand_id: 'byd', model_id: null,
    category: 'Engine System',
    name_en: 'Low Fuel Warning', name_cn: '燃油低警告灯',
    severity: 'INFO',
    description_en: 'The fuel tank is running low (DM-i / DM-p models only).',
    causes: ['Fuel level critically low'],
    can_drive: 'caution',
    action_en: 'Refuel as soon as possible. In DM-i mode, EV range remains available.',
  },
  {
    brand_id: 'byd', model_id: null,
    category: 'Engine System',
    name_en: 'Low Oil Pressure Warning', name_cn: '机油压力低警告灯',
    severity: 'CRITICAL',
    description_en: 'Engine oil pressure is critically low (DM-i / DM-p models).',
    causes: ['Oil level low', 'Oil pump fault', 'Oil leak'],
    can_drive: 'no',
    action_en: 'Stop immediately. Do not run the engine. Check oil level. Call for assistance.',
  },

  // ── Model-specific: BYD Atto 3（元PLUS）────────────────────────────────────
  {
    brand_id: 'byd', model_id: 'byd-atto3',
    category: 'Powertrain',
    name_en: 'Atto 3: High Voltage Interlock Fault', name_cn: '元PLUS：高压互锁故障',
    severity: 'CRITICAL',
    description_en: 'A high-voltage circuit interlock fault specific to the BYD Atto 3.',
    causes: ['High voltage connector not fully seated', 'Wiring harness damage', 'Maintenance cover open'],
    can_drive: 'no',
    action_en: 'Do not drive. Contact BYD dealer immediately.',
  },

  // ── Model-specific: BYD Dolphin（海豚）─────────────────────────────────────
  {
    brand_id: 'byd', model_id: 'byd-dolphin',
    category: 'Body Electronics',
    name_en: 'Dolphin: Gear Selector Fault', name_cn: '海豚：请检查挡位系统',
    severity: 'WARNING',
    description_en: 'The electronic gear selector system on the BYD Dolphin has a fault.',
    causes: ['Gear selector module fault', 'Communication fault between gear selector and VCU'],
    can_drive: 'caution',
    action_en: 'Try cycling power off and on. Book dealer appointment if persists.',
  },

  // ── Model-specific: BYD Han EV（汉EV）──────────────────────────────────────
  {
    brand_id: 'byd', model_id: null,
    category: 'Driver Assist',
    name_en: 'Han EV: Remote Driving Suspended', name_cn: '汉EV：遥控驾驶暂停使用',
    severity: 'INFO',
    description_en: 'The remote driving feature on the BYD Han EV is temporarily unavailable.',
    causes: ['Signal quality insufficient', 'System update in progress', 'Feature disabled'],
    can_drive: 'yes',
    action_en: 'Normal driving is unaffected. Check BYD app for remote driving status.',
  },

  // ── Model-specific: BYD Seal（海豹）────────────────────────────────────────
  {
    brand_id: 'byd', model_id: null,
    category: 'Body Electronics',
    name_en: 'Seal: Memory System Fault', name_cn: '海豹：请检查记忆系统',
    severity: 'INFO',
    description_en: 'The seat/mirror/steering memory system on the BYD Seal has a fault.',
    causes: ['Memory module fault', '12V supply interruption cleared settings'],
    can_drive: 'yes',
    action_en: 'Re-save seat and mirror positions. Book a service if persists.',
  },
]

async function main() {
  console.log(`Seeding ${BYD_LIGHTS.length} BYD warning lights...`)

  for (const light of BYD_LIGHTS) {
    await db.insert(warningLights).values({
      brand_id: light.brand_id,
      model_id: light.model_id ?? null,
      category: light.category,
      name_en: light.name_en,
      name_cn: light.name_cn ?? null,
      severity: light.severity ?? null,
      description_en: light.description_en ?? null,
      causes: light.causes ?? null,
      can_drive: light.can_drive ?? null,
      action_en: light.action_en ?? null,
    })
  }

  console.log('Done.')
}

main().then(() => process.exit(0)).catch((e) => { console.error(e); process.exit(1) })
